const { body, query, param, validationResult } = require('express-validator');

/**
 * Middleware to handle validation errors generated by express-validator.
 * If there are errors, it responds with a 400 Bad Request and an array of error messages.
 * Otherwise, it passes control to the next middleware.
 *
 * @param {Object} req - Express request object
 * @param {Object} res - Express response object
 * @param {Function} next - Express next middleware function
 */
const handleValidationErrors = (req, res, next) => {
  const errors = validationResult(req);
  if (!errors.isEmpty()) {
    return res.status(400).json({
      success: false,
      errors: errors.array().map(err => err.msg)
    });
  }
  next();
};

/**
 * Validation rules for submitting a new complaint.
 */
const validateSubmitComplaint = [
  body('title')
    .notEmpty().withMessage('Title is required')
    .trim()
    .isLength({ max: 200 }).withMessage('Title must be at most 200 characters'),
  body('issue_type')
    .notEmpty().withMessage('Issue type is required')
    .isIn(['pipe_breakage', 'water_leakage', 'water_logging', 'contamination', 'low_pressure']).withMessage('Invalid issue type'),
  body('latitude')
    .notEmpty().withMessage('Latitude is required')
    .isFloat({ min: -90, max: 90 }).withMessage('Latitude must be between -90 and 90')
    .toFloat(),
  body('longitude')
    .notEmpty().withMessage('Longitude is required')
    .isFloat({ min: -180, max: 180 }).withMessage('Longitude must be between -180 and 180')
    .toFloat(),
  body('description').optional().trim(),
  body('address').optional().trim(),
  handleValidationErrors
];

/**
 * Validation rules for user registration.
 */
const validateRegister = [
  body('username')
    .notEmpty().withMessage('Username is required')
    .trim()
    .isLength({ min: 3, max: 50 }).withMessage('Username must be between 3 and 50 characters'),
  body('email')
    .notEmpty().withMessage('Email is required')
    .isEmail().withMessage('Invalid email address')
    .normalizeEmail(),
  body('password')
    .notEmpty().withMessage('Password is required')
    .isLength({ min: 6 }).withMessage('Password must be at least 6 characters'),
  body('phone').optional().trim(),
  handleValidationErrors
];

/**
 * Validation rules for user login.
 */
const validateLogin = [
  body('email')
    .notEmpty().withMessage('Email is required')
    .isEmail().withMessage('Invalid email address')
    .normalizeEmail(),
  body('password')
    .notEmpty().withMessage('Password is required'),
  handleValidationErrors
];

/**
 * Validation rules for responding to a complaint.
 */
const validateRespondToComplaint = [
  body('action_taken').notEmpty().withMessage('Action taken is required').trim(),
  handleValidationErrors
];

/**
 * Validation rules for listing complaints with query parameters.
 */
const validateListComplaints = [
  query('sort_by').optional().isIn(['priority', 'recent']).withMessage('Invalid sort_by value'),
  query('status').optional().isIn(['pending', 'in_progress', 'resolved']).withMessage('Invalid status value'),
  query('page').optional().isInt({ min: 1 }).withMessage('Page must be a positive integer').toInt(),
  query('limit').optional().isInt({ min: 1, max: 100 }).withMessage('Limit must be between 1 and 100').toInt(),
  handleValidationErrors
];

/**
 * Validation rules for updating the status of a complaint.
 */
const validateUpdateStatus = [
  body('status')
    .notEmpty().withMessage('Status is required')
    .isIn(['pending', 'in_progress', 'resolved']).withMessage('Invalid status'),
  handleValidationErrors
];

/**
 * Validation rules for updating a user profile.
 */
const validateUpdateProfile = [
  body('username')
    .optional()
    .trim()
    .isLength({ min: 3, max: 50 }).withMessage('Username must be between 3 and 50 characters'),
  body('phone').optional().trim(),
  handleValidationErrors
];

module.exports = {
  handleValidationErrors,
  validateSubmitComplaint,
  validateRegister,
  validateLogin,
  validateRespondToComplaint,
  validateListComplaints,
  validateUpdateStatus,
  validateUpdateProfile
};
